name: container
on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Open Web Client Directory
        working-directory: packages/container/
         
      - run: npm install
      - run: npm run build
