name: container
on:
  push:
    branches: 
      - main

defaults:
  run:
    working-directory: './packages/container/'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Open Web Client Directory
        working-directory: ../packages/container/
        
        
      - name: Open Web Client Directory
        run: |
          ls -la
          cd ../packages/container/
          ls -la

      - run: npm install
      - run: npm run build
