 
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
   build:
    runs-on: ubuntu-latest    
    defaults:
       run:
         working-directory: ./packages/container/
         
    strategy:
      matrix:
        node-version: [16.x] 

    steps:
    - uses: actions/checkout@v2
    - name: Experiment
      run: |
        pwd   
        cd ../../
        pwd 

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './packages/container/package-lock.json'
        
          
        
    - run: npm ci
      working-directory: './packages/container/'
    - run: npm run start
      working-directory: './packages/container/'
        
             
        
