 
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
     
    
    defaults:
       run:
         working-directory: ./package/

    strategy:
      matrix:
        node-version: [ 16.x ]
         
    

    steps:
    - uses: actions/checkout@v3
    - name: Open Web Client Directory
      run:
        cd ../
      
     
    - name: pwd Nitin
      run:
        pwd
        ls -lha
     
       
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
